TimeControl Sync Bugfix
araex/BannerlordCoop pull request #258
Opened 2022-06-15 10:57 UTC by WakooMan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## What is the current behaviour?

- TimeControl sync does not work.

## What is the new behaviour?

- TimeControl sync now works and TimeCommands written for testing.
## Resolves

- TimeControl bug

## Other information

2022-06-21 17:30 UTC, garrettluskey requested changes

2022-06-21 17:30 UTC, garrettluskey commented on source/CoopFramework/ObjectLifetimeObserver.cs
> +                    var methods = current.GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public).Where(m => m.GetCustomAttributes(typeof(LoadInitializationCallback), false).
This should also get parent class methods, you should be able to remove the while loop and `current = current.BaseType`

2022-06-22 06:40 UTC, WakooMan commented on source/CoopFramework/ObjectLifetimeObserver.cs
> +                    var methods = current.GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public).Where(m => m.GetCustomAttributes(typeof(LoadInitializationCallback), false).
Removed the while loop, but changed the whole thing. Please take a look at it.

2022-06-27 22:14 UTC, garrettluskey requested changes

2022-06-27 22:14 UTC, garrettluskey commented on source/CoopFramework/CoopFramework.cs
> +            loadedAssemblies.ToList().ForEach(a =>
Split these into helper functions. Too many anonymous methods

2022-06-27 22:14 UTC, garrettluskey commented on source/CoopFramework/ObjectLifetimeObserver.cs
> +            Type type = CoopFramework.LoadInitializationCallbacks.Keys.ToList().Find(t => typeof(T) == t);
Try this, you can remove one of the null checks then as well assuming it works as intended

```suggestion
            Type type = CoopFramework.LoadInitializationCallbacks.Keys.ToList().Find(t => t.IsAssignableFrom(typeof(T));
```

2022-06-28 21:59 UTC, WakooMan commented on source/CoopFramework/ObjectLifetimeObserver.cs
> +            Type type = CoopFramework.LoadInitializationCallbacks.Keys.ToList().Find(t => typeof(T) == t);
Done

2022-06-28 22:01 UTC, WakooMan commented on source/CoopFramework/CoopFramework.cs
> +            loadedAssemblies.ToList().ForEach(a =>
foreach cycles are no longer anonymus methods and added one local variable for BindingFlags, so it is easier to read in my opinion.

2022-07-11 18:01 UTC, garrettluskey approved these changes

2022-07-11 18:01 UTC, merged