CoopFramework Synchronization Trigger Change bugfix
araex/BannerlordCoop pull request #259
Opened 2022-06-20 07:43 UTC by WakooMan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## What is the current behaviour?

- When the function is skipped the call is still broadcasted.

## What is the new behaviour?

- When the function is skipped, the call is not broadcasted further.

## Question For Future Problems Probably
- In Dispatch method if one behaviour skips the method, but the list has a behaviour that doesn't skip the method, than should the method be broadcasted?
## Resolves

- CoopFramework Synchronization Trigger Change issue.

## Other information

2022-06-27 22:24 UTC, garrettluskey requested changes

2022-06-27 22:24 UTC, garrettluskey commented on source/CoopFramework/CoopManaged.cs
> +                    prop = behaviour.MethodCallHandler.Invoke(new PendingMethodCall(invokableId,
```suggestion
                    prop = behaviour.MethodCallHandler?.Invoke(new PendingMethodCall(invokableId,
```

2022-06-27 22:24 UTC, garrettluskey commented on source/CoopFramework/CoopManaged.cs
> +                        args));
```suggestion
                        args)) ?? prop; 
```

2022-06-28 22:19 UTC, WakooMan commented on source/CoopFramework/CoopManaged.cs
> +                        args));
Done

2022-06-28 22:19 UTC, WakooMan commented on source/CoopFramework/CoopManaged.cs
> +                    prop = behaviour.MethodCallHandler.Invoke(new PendingMethodCall(invokableId,
Done

2022-08-18 15:38 UTC, garrettluskey commented
Refactoring entire sync framework. Changes no longer required

2022-08-18 15:38 UTC, closed without merging