Equipment,EquipmentElement,ItemRoster,ItemRosterElement,Hideout and BanditPartyComponent Binary Packages Created and Tested
araex/BannerlordCoop pull request #406
Opened 2022-12-02 07:03 UTC by WakooMan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

## What is the new behaviour?

Resolves #399 ,  #391 , #390 , #386 , #383 , #327 , #326

## Other information

2022-12-02 07:07 UTC, WakooMan commented
Equipment and ItemRoster tests are throwing SerializationException, please Joke take a look at why PrimitiveBinaryPackages are created instead of BinaryPackages with type EquipmentElementBinaryPackage and ItemRosterElementBinaryPackage.

2022-12-03 16:46 UTC, garrettluskey requested changes

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/BanditPartyComponentSerializationTest.cs
> +            typeof(Campaign).GetProperty("Current").SetValue(null, FormatterServices.GetUninitializedObject(typeof(Campaign)));
Update this to be similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/CharacterSkillsSerializationTest.cs#L29

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/BanditPartyComponentSerializationTest.cs
> +            typeof(Campaign).GetField("_hideouts", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public).SetValue(Campaign.Current, allhideouts);
Update this to be similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/CharacterSkillsSerializationTest.cs#L29

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/EquipmentElementSerializationTest.cs
> +            MBObjectManager.Instance.Destroy();
Make EquipmentElementSerializationTest IDisposable and move this line there

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/EquipmentElementSerializationTest.cs
> +            MBObjectManager.Init();
Create a constructor for EquipmentElementSerializationTest and move this line there. I didn't think to test it this way, good idea

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/EquipmentSerializationTest.cs
> +            FieldInfo _equipmentType = typeof(Equipment).GetField("_equipmentType", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
Update this to be similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/CharacterSkillsSerializationTest.cs#L29

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/EquipmentSerializationTest.cs
> +            Assert.True(equipment.IsCivilian == newEquipment.IsCivilian && equipment.IsValid == newEquipment.IsValid && (EquipmentType)_equipmentType.GetValue(equipment) == (EquipmentType)_equipmentT
Have multiple `Assert.Equal`, try to avoid multiple conditions in the assert

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/HideoutSerializationTest.cs
> +            Assert.True(hideout == item && hideout.SceneName == item.SceneName && item.IsSpotted == hideout.IsSpotted && _nextPossibleAttackTime.GetValue(hideout) != null);
Have multiple Assert.Equal, try to avoid multiple conditions in the assert

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/HideoutSerializationTest.cs
> +            typeof(Campaign).GetProperty("Current").SetValue(null, FormatterServices.GetUninitializedObject(typeof(Campaign)));
Update this to be similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/CharacterSkillsSerializationTest.cs#L29

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/ItemRosterSerializationTest.cs
> +            MBObjectManager.Init();
Create a constructor for EquipmentElementSerializationTest and move this line there and destroy it in the `Dispose` method

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/BanditPartyComponentSerializationTest.cs
> +            Assert.True(item.IsBossParty == newBanditPartyComponent.IsBossParty == true && newBanditPartyComponent.Hideout != null);
Have multiple Assert.Equal, try to avoid multiple conditions in the assert

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/HideoutSerializationTest.cs
> +            typeof(Campaign).GetField("_hideouts", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public).SetValue(Campaign.Current,allhideouts);
Update this to be similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/CharacterSkillsSerializationTest.cs#L29

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/ItemRosterElementSerializationTest.cs
> +            FieldInfo _amount = typeof(ItemRosterElement).GetField("_amount",BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
Update this to be similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/CharacterSkillsSerializationTest.cs#L29

2022-12-03 16:46 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/ItemRosterElementSerializationTest.cs
> +            Assert.Equal(itemRosterElement,newRosterElement);
add space after `,`

2022-12-03 16:47 UTC, garrettluskey requested changes

2022-12-03 16:47 UTC, garrettluskey commented on source/GameInterface/Serialization/Impl/ItemRosterElementBinaryPackage.cs
> +﻿using Common.Extensions;
Removed unused imports `Ctrl+R, Ctrl+G`

2022-12-03 16:47 UTC, garrettluskey commented on source/GameInterface/Serialization/Impl/ItemRosterBinaryPackage.cs
> +﻿using Common.Extensions;
Removed unused imports `Ctrl+R, Ctrl+G`

2022-12-03 16:47 UTC, garrettluskey commented on source/GameInterface/Serialization/Impl/EquipmentElementBinaryPackage.cs
> +﻿using Common.Extensions;
Removed unused imports `Ctrl+R, Ctrl+G`

2022-12-03 16:47 UTC, garrettluskey commented on source/GameInterface/Serialization/Impl/EquipmentBinaryPackage.cs
> +﻿using Common.Extensions;
Removed unused imports `Ctrl+R, Ctrl+G`

2022-12-03 16:47 UTC, garrettluskey commented on source/GameInterface/Serialization/Impl/BanditPartyComponentBinaryPackage.cs
> +﻿using Common.Extensions;
Removed unused imports `Ctrl+R, Ctrl+G`

2022-12-04 18:53 UTC, garrettluskey requested changes
Still some comments for HideoutSerializationTest

2022-12-04 18:59 UTC, garrettluskey requested changes

2022-12-04 18:59 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/BanditPartyComponentSerializationTest.cs
> +            Assert.True(item.IsBossParty == newBanditPartyComponent.IsBossParty == true);
```suggestion
            Assert.Equal(item.IsBossParty, newBanditPartyComponent.IsBossParty);
```

2022-12-04 18:59 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/BanditPartyComponentSerializationTest.cs
> +            Assert.True(newBanditPartyComponent.Hideout != null);
```suggestion
            Assert.NotNull(newBanditPartyComponent.Hideout);
```

2022-12-04 18:59 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/EquipmentSerializationTest.cs
> +            Assert.True((EquipmentType)_equipmentType.GetValue(equipment) == (EquipmentType)_equipmentType.GetValue(newEquipment));
```suggestion
            Assert.Equal(equipment.IsCivilian, newEquipment.IsCivilian);
            Assert.Equal(equipment.IsValid, newEquipment.IsValid);
            Assert.Equal((EquipmentType)_equipmentType.GetValue(equipment), (EquipmentType)_equipmentType.GetValue(newEquipment));
```

2022-12-05 22:25 UTC, garrettluskey approved these changes

2022-12-05 22:25 UTC, merged