Fix for deploy.ps1 and Coop.csproj
araex/BannerlordCoop pull request #55
Opened 2020-07-16 23:08 UTC by garrettluskey

Verify that this works on your end if the old one also worked.

2020-07-18 08:31 UTC, araex requested changes
The files added to Coop.csproj are missing. I assume the adds should not be included in this pull request. Other than that it seems to work just fine on my end.

2020-07-18 08:31 UTC, araex commented on source/Coop/Coop.csproj
> +    <Compile Include="Mod\CoopServerSM.cs" />
These 2 file adds slipped in i guess?

2020-07-18 16:42 UTC, garrettluskey commented on source/Coop/Coop.csproj
> +    <Compile Include="Mod\CoopServerSM.cs" />
That would be the case

2020-07-19 11:42 UTC, araex approved these changes

2020-07-19 11:42 UTC, merged