Missile crash fix (perhaps)
araex/BannerlordCoop pull request #571
Opened 2023-05-01 12:21 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

## What is the new behaviour?

Resolves #559 maybe?

## Other information

2023-05-02 01:01 UTC, garrettluskey requested changes

2023-05-02 01:01 UTC, garrettluskey commented on source/Missions/Services/Missiles/NetworkMissileRegistry.cs
> +                if (payload.Who != peer) continue;
This will always be true no?

2023-05-02 09:47 UTC, EgardA commented on source/Missions/Services/Missiles/NetworkMissileRegistry.cs
> +                if (payload.Who != peer) continue;
I guess because payload.Who is a an object and not a NetPeer, updated this to instead use the NetPeer ID. The ID's are most of the time the same but there will be missiles in case of two joining at the same time where they might differ.

2023-05-03 00:45 UTC, garrettluskey approved these changes

2023-05-03 07:39 UTC, merged