Settlement Enter/Exit
araex/BannerlordCoop pull request #650
Opened 2023-07-05 12:08 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

Leaving the settlement would crash the game

## What is the new behaviour?

Resolves #647 
Leaving the settlement does not crash the game

## Other information

2023-07-06 14:03 UTC, garrettluskey requested changes

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Client/Services/MobileParties/Messages/SettlementEnterRequest.cs
> +        public string StringId;
Find a more explicit variable name i.e. `SettlementId`

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Patches/EnterSettlementPatch.cs
> +            MessageBroker.Instance.Publish(MobileParty.MainParty, new SettlementEntered(MobileParty.MainParty.TargetSettlement.StringId, MobileParty.MainParty.StringId));
Create message object on different line
```suggestion
            var message = new SettlementEntered(MobileParty.MainParty.TargetSettlement.StringId, MobileParty.MainParty.StringId);
            MessageBroker.Instance.Publish(MobileParty.MainParty, message);
```

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Patches/LeaveSettlementPatch.cs
> +        if(mobileParty.StringId != "TransferredParty") { return true; }
Player party ids will differ, could you find some way to remove this.

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Patches/StartPartyEncounterPatch.cs
> +public class StartPatchEncounterPatch
Also rename file
```suggestion
public class DisablePartyEncounterPatch
```

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/SettlementEntered.cs
> +        public string StringId;
Find a more explicit variable name i.e. `SettlementId`

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Patches/EnterSettlementPatch.cs
> +    public class EnterSettlementPatch
Please add summary comment

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/PartyEnteredSettlement.cs
> +        public string StringId;
Find a more explicit variable name i.e. `SettlementId`

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/SettlementEntered.cs
> +    public record SettlementEntered : IEvent
For any network events, I've been prefixing with `Network`
```suggestion
    public record NetworkPartySettlementEntered : IEvent
```

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Handlers/SettlementExitEnterHandler.cs
> +        private readonly INetwork network;
network is not used, please remove

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/PartyEnteredSettlement.cs
> +    public record PartyEnteredSettlement : ICommand
Commands should be current or future tense
For any network events, I've been prefixing with `Network`
```suggestion
    public record NetworkPartyEnterSettlement : ICommand
```

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Handlers/SettlementExitEnterHandler.cs
> +namespace GameInterface.Services.MapEvents.Handlers
All of the files in `MapEvents` should be moved to `MobileParties`

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/Patches/LeaveSettlementPatch.cs
> +        if(mobileParty.CurrentSettlement == null) { return false; }
This looks like it fixes the party not properly entering the settlement, if you could, find why this is null

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Server/Services/MapEvents/SettlementExitEnterHandler.cs
> +        private readonly ILogger Logger = LogManager.GetLogger<SettlementExitEnterHandler>();
Also I've been moving any static variables before all instance variables
```suggestion
        private static readonly ILogger Logger = LogManager.GetLogger<SettlementExitEnterHandler>();
```

2023-07-06 14:03 UTC, garrettluskey commented on source/GameInterface/Services/MapEvents/SettlementEntered.cs
> +namespace GameInterface.Services.MapEvents
I'm not 100% liking what I do for this, but any network events should exist in the consumer of that event. For this specific one that would be `Coop.Core.Server.Services.MobileParties.Messages`

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Client/Services/MobileParties/Handlers/SettlementExitEnterHandler.cs
> +namespace Coop.Core.Client.Services.MapEvents.Handlers
This should exist in the `MobileParties` service instead of `MapEvents`, let me know if you think otherwise

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Client/Services/MobileParties/Messages/SettlementEnterRequest.cs
> +    public record SettlementEnterRequest : ICommand
For any network events, I've been prefixing with `Network`
```suggestion
    public record NetworkSettlementEnterRequest : ICommand
```

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Server/Services/MapEvents/SettlementExitEnterHandler.cs
> +namespace Coop.Core.Server.Services.MapEvents
This should exist in the `MobileParties` service instead of `MapEvents`, let me know if you think otherwise

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Server/Services/MapEvents/SettlementExitEnterHandler.cs
> +    public class SettlementExitEnterHandler : IHandler
```suggestion
    public class ServerPartyEnterExitSettlementHandler : IHandler
```

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Client/Services/MobileParties/Handlers/SettlementExitEnterHandler.cs
> +    public class SettlementExitEnterHandler : IHandler
```suggestion
    public class ClientPartyExitEnterSettlementHandler : IHandler
```

2023-07-06 14:03 UTC, garrettluskey commented on source/Coop.Core/Client/Services/MobileParties/Messages/SettlementEnterRequest.cs
> +namespace Coop.Core.Client.Services.MapEvents.Messages
The `MapEvents` service shouldn't exist. This is all within the scope of a MobileParty so it should exist in the `MobileParties` service

2023-07-06 14:50 UTC, EgardA commented on source/GameInterface/Services/MapEvents/Patches/LeaveSettlementPatch.cs
> +        if(mobileParty.CurrentSettlement == null) { return false; }
Due to our movement trying to leave the settlement several times (almost certain)

2023-07-06 15:26 UTC, garrettluskey requested changes

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/GameInterface.csproj
> +    <Folder Include="Services\MapEvents\Patches\" />
These shouldn't exist anymore

2023-07-06 15:26 UTC, garrettluskey commented on source/Coop.Core/Server/Services/MobileParties/Handlers/ServerSettlementExitEnterHandler.cs
> +            network.SendAllBut(obj.Who as NetPeer, partyEnteredSettlement);
This should also be sent to the party entering the settlement, if the party enters the settlement without the servers permission, this isn't working as intended

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Messages/PartyEnteredSettlement.cs
> +    public record NetworkPartyEnteredSettlement : ICommand
```suggestion
    public record NetworkPartyEnterSettlement : ICommand
```

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Messages/SettlementEntered.cs
> +    [ProtoContract(SkipConstructor = true)]
This does not need to be a protocontract

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Patches/DisablePartyEncounterPatch.cs
> +using TaleWorlds.CampaignSystem.Encounters;
surely all of these aren't used, try (ctrl+r, ctrl+g)

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Patches/EnterSettlementPatch.cs
> +using GameInterface.Services.MobileParties.Messages;
surely all of these aren't used, try (ctrl+r, ctrl+g)

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Patches/LeaveSettlementPatch.cs
> +using TaleWorlds.CampaignSystem.Encounters;
surely all of these aren't used, try (ctrl+r, ctrl+g)

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Patches/EnterSettlementPatch.cs
> +            return true;
An override method needs to be created here or in `EnterSettlementAction`. This should only be called if it is the server or the `PartySettlementEnter` command is fired

2023-07-06 15:26 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Messages/SettlementEntered.cs
> +    public record SettlementEntered : IEvent
```suggestion
    public record PartySettlementEntered : IEvent
```

2023-07-06 15:26 UTC, garrettluskey commented on source/Coop.Core/Coop.Core.csproj
> +    <Folder Include="Server\Services\MapEvents\Messages\" />
These shouldn't exist anymore

2023-07-06 15:26 UTC, garrettluskey commented on source/Coop.Core/Coop.Core.csproj
> +    </Reference>
In `Coop.Core` there should be no references to the game

2023-07-06 15:26 UTC, garrettluskey commented on source/Coop.Core/Coop.Core.csproj
> +    </Reference>
In `Coop.Core` there should be no references to the game

2023-07-06 15:35 UTC, garrettluskey requested changes

2023-07-06 15:35 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Handlers/SettlementExitEnterHandler.cs
> +            messageBroker.Subscribe<NetworkPartyEnteredSettlement>(Handle);
The game interface should not know about the network, this should be handled in `Coop.Core.Client`
A new event will have to be created that this class will catch that is fired by the handler in `Coop.Core.Client`

2023-07-10 00:47 UTC, garrettluskey approved these changes

2023-07-10 00:48 UTC, merged