VillageState Sync
araex/BannerlordCoop pull request #654
Opened 2023-07-08 22:28 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

## What is the new behaviour?

Resolves #

## Other information

2023-07-13 22:48 UTC, garrettluskey requested changes

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +            if (village == _allowedInstance?.Instance) return true;
We now have a method for checking if allowed

```suggestion
            if (_allowedInstance.IsAllowed(village)) return true;
```

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +        private static readonly MethodInfo _applyInternal = typeof(ChangeVillageStateAction).GetMethod("ApplyInternal", BindingFlags.NonPublic | BindingFlags.Static);
I don't remember if this works with statics but give it a try. If not let me know and keep as is.

I want any calls that happen a lot to use delegates as reflection invoke is fairly slow

```suggestion
        private static MethodInfo _applyInternal => typeof(ChangeVillageStateAction).GetMethod("ApplyInternal", BindingFlags.NonPublic | BindingFlags.Static);
        private static readonly Action<Village, Village.VillageStates, MobileParty> ApplyInternalDelegate = _applyInternal .BuildDelegate<Action<Village, Village.VillageStates, MobileParty>>();
```

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/VillageStateChanged.cs
> +    public record VillageStateChanged : IEvent
Please add summary comments

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageStateRequest.cs
> +    public record ChangeVillageStateRequest : ICommand
Please add summary comments

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageStateApproved.cs
> +    public record ChangeVillageStateApproved : ICommand
Please add summary comments

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageState.cs
> +    public record ChangeVillageState : IEvent
Please add summary comments

2023-07-13 22:48 UTC, garrettluskey commented on source/Coop.Core/Client/Messages/ChangeVillageStateApproved.cs
> +    public record ChangeVillageStateApproved : ICommand
Please add summary comments

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageStateRequest.cs
> +namespace GameInterface.Services.Villages.Messages
This shouldn't be in game interface

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageStateApproved.cs
> +namespace Coop.Core.Client.Messages
This shouldn't be in game interface

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +        private static AllowedInstance<Village> _allowedInstance;
```suggestion
        private readonly static AllowedInstance<Village> _allowedInstance = new AllowedInstance<Village>();
```

2023-07-13 22:48 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +            using (_allowedInstance = new AllowedInstance<Village>(village))
```suggestion
            using (_allowedInstance.Instance = village)
```

2024-01-16 04:33 UTC, garrettluskey requested changes

2024-01-16 04:33 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Handlers/VillageHandler.cs
> +            Village village = Village.All.Find(x => x.StringId == obj.What.VillageId);
This is fairly slow, can you use objectManager instead? Settlements should all be registered

2024-01-16 04:33 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +            using (_allowedInstance)
Update allowed instance to AllowedThread after https://github.com/Bannerlord-Coop-Team/BannerlordCoop/pull/723 is merged

2024-01-16 04:33 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +            MessageBroker.Instance.Publish(village, new ChangeVillageState(village.StringId, Convert.ToInt32(newState), raiderParty.StringId));
This event should be `VillageStateChanged`

2024-01-16 04:33 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/ChangeVillageStatePatch.cs
> +    [HarmonyPatch(typeof(ChangeVillageStateAction), "ApplyInternal")]
Instead sync `VillageState` setter

You can keep this patch but update prefix to `private static bool Prefix() => ModInformation.IsServer`

2024-01-16 04:33 UTC, garrettluskey commented on source/Coop.Core/Client/Services/Villages/Messages/ChangeVillageStateRequest.cs
> +    public record ChangeVillageStateRequest : ICommand
This should be server side only, no need for client requests

2024-01-16 08:52 UTC, closed without merging

2024-01-16 08:53 UTC, EgardA commented
Closed, as this would instead be a part of MapEvent