Join messages
araex/BannerlordCoop pull request #695
Opened 2023-10-30 10:04 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

Some join messages

## What is the new behaviour?

Resolves #684 

## Other information

2023-11-03 04:04 UTC, garrettluskey commented
Currently tests are failing and requirement 2 in #684 is not covered as far as I can tell

2023-11-04 01:27 UTC, EgardA commented
You are correct, fixing.

2023-12-11 22:06 UTC, garrettluskey requested changes

2023-12-11 22:06 UTC, garrettluskey commented on source/Coop.Core/Client/States/MainMenuState.cs
> +        messageBroker.Publish(this, new SendInformationMessage("A new player is joining the game, pausing"));
Instead create a JoinMessage service that subscribes to the same events. This is separate functionality than the states here

2023-12-15 02:28 UTC, garrettluskey requested changes

2023-12-15 02:28 UTC, garrettluskey commented on source/Coop.Core/Server/Connections/ClientRegistry.cs
> +        messageBroker.Publish(this, new SendInformationMessage("A new player is joining the game, pausing"));
Separate this into a separate service as well

2023-12-15 02:28 UTC, garrettluskey commented on source/Coop.Tests/Server/Connections/States/LoadingStateTests.cs
> +            Assert.True(MockMessageBroker.PublishedMessages.Count == 2);
Revert this please

2023-12-15 02:28 UTC, garrettluskey commented on source/Coop.Core/Server/Services/Time/Handlers/TimeHandler.cs
> +        }
These should be in the same class

2023-12-15 02:28 UTC, garrettluskey commented on source/Coop.Core/Server/Services/Time/Handlers/TimeHandler.cs
> +        }
These should be in the same class

2023-12-15 02:28 UTC, garrettluskey commented on source/Coop.Core/Server/Services/Players/Handlers/PlayerConnectionServerMessageHandler.cs
> +            }
These should be in the same class

2023-12-15 02:28 UTC, garrettluskey commented on source/Coop.Core/Server/Connections/States/LoadingState.cs
> +    private readonly INetwork network;
These likely aren't used anymore

2023-12-15 02:40 UTC, garrettluskey commented
All of the logging should exist in the same class. Having all the functionality in a single place makes it easier to maintain and not add lines to unrelated classes

2023-12-20 21:24 UTC, garrettluskey requested changes

2023-12-20 21:24 UTC, garrettluskey commented on source/Coop.Core/Common/Services/Connection/Handlers/PlayerConnectionServerMessageHandler.cs
> +            }
this logic only works on the server

2023-12-20 21:24 UTC, garrettluskey commented on source/Coop.Core/Common/Services/Connection/Handlers/PlayerConnectionServerMessageHandler.cs
> +            }
this logic only works on the server

2023-12-20 21:24 UTC, garrettluskey commented on source/Coop.Core/Common/Services/Connection/Handlers/PlayerConnectionServerMessageHandler.cs
> +    public class PlayerConnectionServerMessageHandler
This class is never initialized, move to the server directory and have this class inherit IHandler to be collected by https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/Coop.Core/Server/ServerModule.cs#L34

2023-12-20 21:24 UTC, garrettluskey commented on source/Coop.Core/Common/Services/Connection/Handlers/PlayerConnectionServerMessageHandler.cs
> +            messageBroker.Publish(this, new SendInformationMessage("A new player is joining the game, pausing"));
The game does not pause exactly when a player connects, the game instead pauses [here](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/Coop.Core/Server/Connections/States/TransferSaveState.cs#L27)

2023-12-20 21:24 UTC, garrettluskey commented on source/Coop.Core/Common/Services/Connection/Handlers/PlayerConnectionServerMessageHandler.cs
> +                messageBroker.Publish(this, new SendInformationMessage("All players connected, game can now be un-paused"));
2x of same string, separate into variable

2023-12-20 21:24 UTC, garrettluskey commented on source/Coop.Core/Common/Services/Connection/Handlers/PlayerConnectionServerMessageHandler.cs
> +                messageBroker.Publish(this, new SendInformationMessage("Pausing disabled, " + loadingPeers + " player(s) are currently joining the game"));
2x of same string, separate into variable

2023-12-26 17:19 UTC, garrettluskey requested changes

2023-12-26 17:19 UTC, garrettluskey commented on source/Coop.Core/Coop.Core.csproj
> +  </ItemGroup>
Could you remove this? this will keep that unused folder in the project

2023-12-26 18:07 UTC, merged