WIP: VillageState Sync
araex/BannerlordCoop pull request #730
Opened 2024-01-16 21:57 UTC by samuelzurowski

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Adds currently the villagestate sync

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?
When a VillageState is changed it is hooked and goes through the message broker to update the client. Additionally server commands are now added.

## What is the new behaviour?
Partially Resolves #727 

## Other information

2024-01-16 22:30 UTC, garrettluskey requested changes

2024-01-16 22:30 UTC, garrettluskey commented on source/Coop.Core/Coop.Core.csproj
> +  </ItemGroup>
```suggestion
```

2024-01-16 22:30 UTC, garrettluskey commented on source/Coop.Core/Coop.Core.csproj
> +	  </Reference>
There should be no references to TaleWorlds in Coop.Core
```suggestion
```

2024-01-16 22:30 UTC, garrettluskey commented on source/Coop.IntegrationTests/Villages/VillageStateTest.cs
> +    /// Use for server controlled functionality
Please update comment

2024-01-16 22:30 UTC, garrettluskey commented on source/Coop.IntegrationTests/Villages/VillageStateTest.cs
> +    public void ServerReceivesTemplateEventMessage_PublishesTemplateCommandMessage_AllClients()
Update template name

2024-01-16 22:30 UTC, garrettluskey commented on source/GameInterface/GameInterfaceModule.cs
> +
```suggestion
```

2024-01-16 22:30 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageState.cs
> +/// This is used when the Client Sends the GameInterface data to change its state.
We shouldn't reference server/client in the events as they are meant to be a generic API of sorts
```suggestion
/// Updates the village state
```

2024-01-16 22:30 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/VillagePatches.cs
>      }
This does the same thing

```suggestion
    private static bool DailyTickPrefix() => ModInformation.IsServer;
```

2024-01-16 22:30 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/VillagePatches.cs
>          return false;
```suggestion
        if (ModInformation.IsClient) return false;
        
        var message = new VillageStateChanged(__instance.Settlement.StringId, (int)__instance.VillageState);
        MessageBroker.Instance.Publish(__instance, message);    
        return true;
```

2024-01-16 22:30 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/VillageStateChanged.cs
> +/// This is used when the server needs to update the VillageStates to the client
```suggestion
/// This event is fired when the village state is updated
```

2024-01-16 22:30 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Handlers/VillageStateHandler.cs
> +        // The current implementation
Resolve the TODO

2024-01-16 22:30 UTC, garrettluskey commented on source/Coop.Core/Server/Services/Villages/Handlers/ServerVillageStateHandler.cs
> +
```suggestion
```

2024-01-16 22:30 UTC, garrettluskey commented on source/Coop.Core/Server/Services/Villages/Handlers/ServerVillageStateHandler.cs
> +
Remove template comment
```suggestion
```

2024-01-16 22:50 UTC, samuelzurowski commented
@garrettluskey all set.

2024-01-16 22:50 UTC, samuelzurowski commented
@garrettluskey However, technically not ready until settlements are kept track of.

2024-01-19 19:27 UTC, samuelzurowski commented
@garrettluskey should be good.

2024-01-20 21:10 UTC, garrettluskey requested changes

2024-01-20 21:10 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/VillagePatches.cs
> +    private static bool BoundPrefix() => true;
Add syncing for bound as well, some mods may update this

2024-01-20 21:19 UTC, garrettluskey requested changes

2024-01-20 21:19 UTC, garrettluskey commented on source/Coop.Core/Client/Services/Villages/Handlers/ClientVillageHandler.cs
> +        public void Dispose()
Add all subscriptions to the dispose method, I recommend having Dispose right below the constructor to make this more obvious

2024-01-20 21:19 UTC, garrettluskey commented on source/Coop.Core/Server/Services/Villages/Handlers/ServerVillageHandler.cs
> +        public void Dispose()
Add all subscriptions to the dispose method, I recommend having Dispose right below the constructor to make this more obvious

2024-01-20 21:19 UTC, garrettluskey commented on source/Coop.IntegrationTests/Villages/VillageLastDemandTimeSatisifiedTest.cs
> +    public void ServerLastDemandTimeChanged_Publishes_AllClients()
Please add summary comments

2024-01-20 21:19 UTC, garrettluskey commented on source/GameInterface.Tests/Serialization/SerializerTests/VillageSerializerTest.cs
> +using GameInterface.Policies;
likely not used import

2024-01-20 21:19 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Handlers/VillageHandler.cs
> +    public void Dispose()
Add all subscriptions to the dispose method, I recommend having Dispose right below the constructor to make this more obvious

2024-01-20 21:19 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/VillageHearthChanged.cs
> +public record VillageHearthChanged : ICommand
please add summary comment

2024-01-20 21:19 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageTradeBound.cs
> +    public record ChangeVillageTradeBound : ICommand
please add summary comment

2024-01-20 21:19 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Messages/ChangeVillageHearth.cs
> +public record ChangeVillageHearth : ICommand
Please add summary comments

2024-01-20 22:11 UTC, garrettluskey commented on source/GameInterface/Services/Villages/Patches/VillagePatches.cs
> +    private static bool BoundPrefix() => true;
I have changed my mind on this, not required. If already half way through feel free to complete otherwise it's ok to exclude this functionality

2024-01-21 16:57 UTC, garrettluskey approved these changes

2024-01-21 17:04 UTC, merged