741 army joinleave sync
araex/BannerlordCoop pull request #754
Opened 2024-02-05 18:45 UTC by thomas-soutif

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

No sync when a mobile party join an army, or leave it

## What is the new behaviour?

Resolves #741

Sync when a party join an army, and a party leave an army

## Other information

2024-02-09 01:18 UTC, garrettluskey requested changes

2024-02-09 01:18 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Commands/ArmyDebugCommand.cs
> +            return stringBuilder.ToString();
```suggestion
            return "Usage: coop.debug.army.mobile_party_list <ArmyId>";
```

2024-02-09 01:18 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Commands/ArmyDebugCommand.cs
> +            return stringBuilder.ToString();
```suggestion
            return "Usage: coop.debug.army.mobile_party_add <ArmyId> <MobilePartyId>";
```

2024-02-09 01:18 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Commands/ArmyDebugCommand.cs
> +            return stringBuilder.ToString();
```suggestion
            return "Usage: coop.debug.army.mobile_party_remove <ArmyId> <MobilePartyId>";
```

2024-02-09 01:18 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Patches/ArmyPatches.cs
> +
Remove dead code and use army extension
```suggestion
                army.AddPartyInternal(mobileParty);

```

2024-02-09 01:18 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Extensions/ArmyExtensions.cs
> +    internal static void RemovePartyInternal(MobileParty mobileParty, Army army)
make this into an army extension
```suggestion
    internal static void RemovePartyInternal(this Army army, MobileParty mobileParty)
```

2024-02-09 01:18 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Extensions/ArmyExtensions.cs
> +    internal static void AddPartyInternal(MobileParty mobileParty, Army army)
```suggestion
    internal static void AddPartyInternal(this Army army, MobileParty mobileParty)
```

2024-02-14 23:06 UTC, thomas-soutif commented
still have the bug when party add to army : duplication found
I've tried to send the List of Parties and setting it with the client every time a parties is add (to have the same list), it works almost fine, but there's a bug where sometimes, an army is not retrieve in the store (client side), so the mobile party cannot be add to the client army

This is the code I use to set directly a list (to give some idea) : 
```c#
internal static void AddPartyList(this Army army, List<MobileParty> mobilePartyListToUpdate)
{
    //Army_OnAddPartyInternal(army,mobileParty);
    
    // Get the _parties field using reflection
    FieldInfo partiesField = typeof(Army).GetField("_parties", BindingFlags.NonPublic | BindingFlags.Instance);

    
    MBList<MobileParty> newList = new MBList<MobileParty>();
    foreach (MobileParty party in mobilePartyListToUpdate)
    {
        newList.Add(party);
    }
    partiesField.SetValue(army, newList);
    
}
```

2024-02-15 12:17 UTC, thomas-soutif commented
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/d669d5d0-cbcb-4cce-8dae-a6c605fe5d81)

Has we can see, the main problem is that the client receive first mobile party add to army, before receiving the message to create the Army.
Here, the Army the Object Manager try to get is the CoopArmy_3
But in the game states, there's only 2 army the client have : The CoopArmy_1 and the CoopArmy_2

A solution could be to add a queue for mobile party add to army. Like this, if the army is not found because the client does not received it yet, it put it in a queue, and try later to add it (500ms or 1 second later)

2024-02-15 13:12 UTC, thomas-soutif commented
I've implement the a ArmyQueueManager to solved the issue I told before. Open for discussion, on optimization etc

2024-02-15 21:46 UTC, thomas-soutif commented
Duplication fixed, and also the add / remove party sync

2024-02-16 11:41 UTC, thomas-soutif commented
I've tested the new commits from @garrettluskey,
The sync of the army works well, the server is waiting for all clients to have the army created, but it creates also a big freeze every time an army is created (I think keeping the creation async with a queue system would be better for player experience)

The sync of mobile parties doesn't work well, a lot of duplication, parties are add to the army from nowhere( for the client).
@garrettluskey said it will be unstable until we fully sync all **party**, **hero** and **army data**. 

Finally, we cannot debug the game because of a crash that happened very quickly :
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/34a10779-53b5-4bc2-a607-71232ceebb2c)
I was able to have 2 army created, but then a crash

I cleaned the project, and created a new party before test all of this.
So for now I don't know what we're doing with this branch, it's too unstable to be merge to the develop, and I'll not continue working on it if the rest is not implemented. So I propose to make a pause with this branch and start working on the other dependencys, I wait for the rest

2024-02-17 18:47 UTC, garrettluskey approved these changes

2024-02-17 18:47 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Patches/ArmyPatches.cs
> +            return false;
If there is a failure this should return true to allow original method

2024-02-17 18:47 UTC, garrettluskey commented on source/GameInterface/Services/Armies/Patches/ArmyPatches.cs
> +            return false;
If there is a failure this should return true to allow original method

2024-02-17 18:47 UTC, garrettluskey approved these changes

2024-02-17 18:48 UTC, merged