WIP: Kingdom decision sync
araex/BannerlordCoop pull request #755
Opened 2024-02-07 06:02 UTC by WakooMan

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

## What is the new behaviour?

Resolves #748 #671 

- KingdomDecisions can be serialized now.
- AddDecision and RemoveDecision method is now synced.

## Other information

2024-02-09 01:26 UTC, garrettluskey requested changes

2024-02-09 01:26 UTC, garrettluskey commented on source/Coop.Core/Client/Services/Kingdoms/Handlers/ClientKingdomDecisionHandler.cs
> +    public class ClientKingdomDecisionHandler : IHandler
Add summary comments to all new classes then good to go

2024-02-09 01:26 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Patches/KingdomPatches.cs
> +            using (AllowedInstance)
Use allowed thread instead https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Services/Armies/Patches/ArmyCreationPatch.cs#L160

2024-02-09 01:26 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Patches/KingdomPatches.cs
> +            using (AllowedInstance)
Use allowed thread instead https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Services/Armies/Patches/ArmyCreationPatch.cs#L160

2024-02-09 01:26 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Patches/KingdomPatches.cs
> +            if (AllowedInstance.IsAllowed(__instance)) return true;
Use allowed thread instead https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Services/Armies/Patches/ArmyCreationPatch.cs#L38

2024-02-09 01:26 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Patches/KingdomPatches.cs
> +            if (AllowedInstance.IsAllowed(__instance)) return true;
Use allowed thread instead https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Services/Armies/Patches/ArmyCreationPatch.cs#L38

2024-03-02 22:36 UTC, garrettluskey requested changes
Also fix conflicts and good to go

Allow origianl has been condensed to the following

```CS
// Skip if we called it
if (CallOriginalPolicy.IsOriginalAllowed()) return true;
```

2024-03-02 22:36 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Messages/LocalDecisionAdded.cs
> +        public LocalDecisionAdded(string kingdomId, KingdomDecisionData data, bool ignoreInfluenceCost)
```suggestion
        public DecisionAdded(string kingdomId, KingdomDecisionData data, bool ignoreInfluenceCost)
```

2024-03-02 22:36 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Messages/LocalDecisionRemoved.cs
> +        public LocalDecisionRemoved(string kingdomId, int index)
```suggestion
        public DecisionRemoved(string kingdomId, int index)
```

2024-03-02 22:36 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Messages/AddDecision.cs
> +    public class AddDecision: IEvent
```suggestion
    public class AddDecision: ICommand
```

2024-03-02 22:36 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Messages/RemoveDecision.cs
> +    public class RemoveDecision: IEvent
```suggestion
    public class RemoveDecision: ICommand
```

2024-03-02 22:36 UTC, garrettluskey commented on source/GameInterface/Services/Kingdoms/Extentions/KingdomDecisionExtensions.cs
> +            }
```suggestion
            if (SupportedConversions.TryGetValue(kingdomDecision.GetType(), out var conversionFn) == false)
            {
                throw new InvalidOperationException($"Type of kingdom decision: {kingdomDecision.GetType().Name} is not supported.");
            }
            
            return conversionFn(kingdomDecision);
```

2024-03-02 22:39 UTC, MaxDorob requested changes, later dismissed

2024-03-02 22:39 UTC, MaxDorob commented on source/GameInterface/Services/Heroes/Patches/HeroPatches.cs
> +        private static bool IsHumanPlayerCharacterPrefix(Hero __instance, bool __result)
```suggestion
        private static bool IsHumanPlayerCharacterPrefix(Hero __instance, ref bool __result)
```
Afaik result won't be changed without ref

2025-01-20 21:05 UTC, garrettluskey approved these changes
Looks me to good

2025-01-20 21:58 UTC, merged