Working test
araex/BannerlordCoop pull request #789
Opened 2024-03-13 01:26 UTC by garrettluskey

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behaviour?

MobileParty Collections are not synced over the network

## What is the new behaviour?

Resolves #785

Syncs mobile party collections

## Other information

2024-03-13 10:41 UTC, EgardA requested changes

2024-03-13 10:41 UTC, EgardA commented on source/GameInterface/Services/MobileParties/Handlers/MobilePartyAttachedPartyHandler.cs
> +/// TODO
Very good comment

2024-03-14 03:44 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Handlers/MobilePartyAttachedPartyHandler.cs
> +/// TODO
Updated

2024-03-14 13:09 UTC, EgardA approved these changes

2024-03-14 13:09 UTC, merged