Bandit Party Component Sync
araex/BannerlordCoop pull request #823
Opened 2024-07-24 21:51 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behavior?

No bandit party component sync

## What is the new behavior?

Resolves #794 

bandit party component sync

## Other information

2024-07-24 21:56 UTC, EgardA commented
I left out _relatedSettlement on purpose, it is only assigned on creation.

2024-07-26 02:05 UTC, garrettluskey requested changes

2024-07-26 02:05 UTC, garrettluskey commented on source/E2E.Tests/Services/MobileParties/BanditPartyComponentTests.cs
> +        var settlement = GameObjectCreator.CreateInitializedObject<Settlement>();
This isn't guaranteed to run on the server, could you add this in a server.call statement?

2024-07-26 02:05 UTC, garrettluskey commented on source/E2E.Tests/Util/ObjectBuilders/BanditPartyComponentBuilder.cs
> +            .Invoke(partyComponent, new object[] { settlement });
Doesn't this work?

```suggestion
        return new BanditPartyComponent(settlement)
```

2024-07-26 22:55 UTC, garrettluskey requested changes

2024-07-26 22:55 UTC, garrettluskey commented on source/E2E.Tests/Services/MobileParties/BanditPartyComponentTests.cs
> +        });
```suggestion
        string componentId = TestEnvironment.CreateRegisteredObject<BanditPartyComponent>();
        string hideoutId = TestEnvironment.CreateRegisteredObject<Hideout>();
        string settlementId = TestEnvironment.CreateRegisteredObject<Settlement>();
```

**Then use the ids to resolve the objects in the clients scope**

2024-07-27 11:11 UTC, georgyrudnev commented on source/E2E.Tests/Services/PartyComponents/BanditPartyComponentTests.cs
In lines 125-129, arent you just testing against the variables you created before?
Shouldnt you be testing against the client values through client.ObjectManager.TryGetObject ?

2024-07-27 11:18 UTC, EgardA commented on source/E2E.Tests/Services/PartyComponents/BanditPartyComponentTests.cs
You are correct, I will fix that :)

2024-07-28 21:31 UTC, merged