Workshop Properties
araex/BannerlordCoop pull request #961
Opened 2024-09-04 23:28 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behavior?

No workshop properties

## What is the new behavior?

Resolves #937 

## Other information

2024-09-06 19:32 UTC, EgardA commented
This still has some work, hold off for now

2024-09-07 23:32 UTC, garrettluskey requested changes

2024-09-07 23:32 UTC, garrettluskey commented on source/E2E.Tests/Services/Workshops/WorkshopPropertyTests.cs
> +            WorkshopTypeId2 = typeId2;
```suggestion
            Server.ObjectManager.AddNewObject(workshopType, out WorkshopTypeId);
            Server.ObjectManager.AddNewObject(workshopType2, out  WorkshopTypeId2);
            Server.ObjectManager.AddNewObject(workshop, out WorkshopId);

            WorkshopId = workshopId;
            WorkshopTypeId = typeId;
            WorkshopTypeId2 = typeId2;
```

2024-09-07 23:32 UTC, garrettluskey commented on source/E2E.Tests/Services/Workshops/WorkshopPropertyTests.cs
> +        string WorkshopTypeId2 { get; set; }
```suggestion
        string WorkshopId { get; }
        string WorkshopTypeId { get; }
        string WorkshopTypeId2 { get; }
```

2024-09-07 23:32 UTC, garrettluskey commented on source/GameInterface/Services/Workshops/Patches/WorkshopPropertyPatches.cs
> +    public class WorkshopPropertyPatches
We need the following properties synced still.
Also for future reference could you comment in the issue why you are skipping some sync?

- InitialCapital (set in the constructor which requires sync)
- Capital (set in the constructor which requires sync)

2024-09-08 20:20 UTC, EgardA commented
Do not merge until WorkshopType has been synced

2024-09-24 01:46 UTC, garrettluskey approved these changes

2024-09-24 01:46 UTC, merged