Crafting Lifetime
araex/BannerlordCoop pull request #968
Opened 2024-09-12 11:19 UTC by EgardA

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behavior?

No crafting lifetime sync

## What is the new behavior?

Resolves #855 

## Other information

2024-09-14 22:55 UTC, garrettluskey requested changes

2024-09-14 22:55 UTC, garrettluskey commented on source/GameInterface/Services/CultureObjects/Patches/CultureObjectLifetimePatches.cs
> +        [HarmonyPatch(typeof(CultureObject), MethodType.Constructor)]
Add destruction postfix patches for the following
- CreatePreCraftedWeapon
- InitializePreCraftedWeaponOnLoad
- CreateRandomCraftedItem

Add a destruction prefix for CraftingState.CraftingLogic setter, and delete the current CraftingLogic value (if it is not null)

2024-09-15 01:00 UTC, garrettluskey requested changes

2024-09-15 01:00 UTC, garrettluskey commented on source/GameInterface/Services/CraftingService/Patches/CraftingDestructionPatches.cs
> +    internal class CraftingDestructionPatches
This is technically a lifetime patch, could you move these into the Lifetime file?

2024-09-15 01:02 UTC, garrettluskey requested changes

2024-09-15 01:02 UTC, garrettluskey commented on source/GameInterface/Services/CraftingService/Patches/CraftingDestructionPatches.cs
> +            }
Can you instead put the instance into the message and resolve using the object manager in the broker?

2024-09-15 10:17 UTC, georgyrudnev commented on source/GameInterface/Services/CraftingTemplates/Patches/CraftingTemplateLifetimePatches.cs
I think line 33 you don´t need to resolve object manager since it is not used neither here nor in cultureObject patch.
Or alternatively if we need to track it in the object manager we should add it there like in craftingLifetimePatches.

2024-09-15 14:54 UTC, garrettluskey requested changes

2024-09-15 14:54 UTC, garrettluskey commented on source/GameInterface/Services/CraftingService/Handlers/CraftingHandler.cs
> +            objectManager.Remove(payload.What.crafting);
What if these fail?

Can you add logging and returns if these fail

2024-09-15 14:54 UTC, garrettluskey commented on source/GameInterface/Services/CraftingService/Patches/CraftingLifetimePatches.cs
> +            }
Can you pass up the instances to the lifetime handler and resolve the ids in there?

2024-09-15 14:54 UTC, garrettluskey commented on source/GameInterface/Services/CraftingTemplates/Handlers/CraftingTemplateLifetimeHandler.cs
> +            objectManager.AddNewObject(payload.What.CraftingTemplate, out string newId);
What if this fails?

2024-09-15 14:54 UTC, garrettluskey commented on source/GameInterface/Services/CraftingTemplates/Patches/CraftingTemplateLifetimePatches.cs
> +            if (ContainerProvider.TryResolve<IObjectManager>(out var objectManager))
This isn't used, please remove

2024-09-15 14:54 UTC, garrettluskey commented on source/GameInterface/Services/CultureObjects/Handlers/CultureObjectHandler.cs
> +            objectManager.AddNewObject(payload.What.CultureObject, out string newId);
What if this fails?

2024-09-15 14:54 UTC, garrettluskey commented on source/GameInterface/Services/CultureObjects/Handlers/CultureObjectHandler.cs
> +            objectManager.AddExisting(payload.CultureObjectId, newCultureObject);
What if this fails
```suggestion
            if (objectManager.AddExisting(payload.CultureObjectId, newCultureObject) == false) return;
```

2024-09-18 02:15 UTC, garrettluskey requested changes

2024-09-18 02:15 UTC, garrettluskey commented on source/GameInterface/Services/CraftingService/Patches/CraftingLifetimePatches.cs
> +            if (CallOriginalPolicy.IsOriginalAllowed()) return true;
I would add this to the post fixes just to be safe, then this is good to go

2024-09-18 02:15 UTC, garrettluskey commented on source/GameInterface/Services/CraftingTemplates/Handlers/CraftingTemplateLifetimeHandler.cs
> +    public class CraftingTemplateLifetimeHandler : IHandler
Can you add a test for crafting template?

2024-09-18 02:15 UTC, garrettluskey commented on source/GameInterface/Services/CultureObjects/Handlers/CultureObjectHandler.cs
> +    internal class CultureObjectHandler : IHandler
Can you rename this to CultureObjectLifetimeHandler and create a test? MBObjectManager is the fallback in our IObjectManager so we may not even need this class but if that doesn't work we do need this

2024-09-19 01:06 UTC, garrettluskey approved these changes, later dismissed
LGTM

2024-09-19 01:07 UTC, garrettluskey commented
If tests pass good to merge

2024-09-25 18:38 UTC, merged