799 sync militia party component
araex/BannerlordCoop pull request #998
Opened 2024-10-12 18:21 UTC by georgyrudnev

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] All new classes have class-level documentation comments, if there are any at all
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation update
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

Resolves #

## Other information

2024-10-14 18:19 UTC, georgyrudnev commented
MilitiaPartyComponent constructor on the server is not triggering the Settlement property setter patch as expected. Client-side instance creation skipping the constructor is working as designed. Issue lies in serveside behavior, where the settlemt property setter should be called during construction triggering our prefix patch for syncing the property. This is not happening preventing proper synchronization of the Settlement property to clients. Need to investigate why  server-side setter is not triggering our patch during the component's construction.

2024-11-11 13:59 UTC, EgardA requested changes

2024-11-11 13:59 UTC, EgardA commented on source/ClientDebug/ClientDebug.csproj.user
> +    <StartProgram>E:\Bannerlord COOP\mb2\bin\Win64_Shipping_Client\Bannerlord.exe</StartProgram>
Please revert these back

2024-11-11 13:59 UTC, EgardA commented on source/Coop/Coop.csproj.user
> +    <StartWorkingDirectory>E:\Bannerlord COOP\mb2\bin\Win64_Shipping_Client\</StartWorkingDirectory>
Revert these as well

2024-11-13 01:43 UTC, garrettluskey requested changes

2024-11-13 01:43 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Patches/MobilePartyPropertyPatches.cs
>      private static bool SetCurentSettlementPrefix(MobileParty __instance, Settlement value)
```suggestion
    private static bool SetCurrentSettlementPrefix(MobileParty __instance, Settlement value)
```

2024-11-13 01:43 UTC, garrettluskey commented on source/GameInterface/Services/PartyComponents/Data/PartyComponentData.cs
can you undo the changes in this file as these imports are not used?

2024-11-13 01:43 UTC, garrettluskey commented on source/GameInterface/Services/Towns/Handlers/TownHandler.cs
> +                }
```suggestion
                if (obj.GovernorId && objectManager.TryGetObject(obj.GovernorId, out Hero governor) == false)
                {
                    Logger.Error("Unable to find Hero ({governorId})", obj.GovernorId);
                    return;
                }
```

2024-11-13 01:44 UTC, garrettluskey commented
Anyway to use autosync instead?

2024-11-20 00:06 UTC, garrettluskey requested changes

2024-11-20 00:06 UTC, garrettluskey commented on source/GameInterface/Services/MobileParties/Patches/MobilePartyPropertyPatches.cs
> +        if (value == __instance._currentSettlement) return false;
Please revert this file, the new lines make it easier to read
But please keep the new lines and [this update](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/pull/998/files#diff-591d596d28072d88f4e09d9a435374d77eebb1e11f5a9ea3f97279bb7b24f063R101) as well

2024-11-20 00:06 UTC, garrettluskey commented on source/GameInterface/GameInterface.csproj
> +  </ItemGroup>
Revert this file

2024-11-20 00:06 UTC, garrettluskey commented on source/GameInterface/Services/PartyComponents/Handlers/PartyComponentHandler.cs
> +        }
This is no longer needed since the Settlement is autosynced, please remove

2024-11-20 00:06 UTC, garrettluskey commented on source/GameInterface/Services/PartyComponents/Patches/Lifetime/MilitiaPartyComponentLifetimePatches.cs
Please revert this file. settlement.stringid is not needed in the message

2024-11-20 00:06 UTC, garrettluskey commented on source/GameInterface/Services/Settlements/Patches/MobilePartyCachePatch.cs
>      private static bool AddMobilePartyPrefix(ref Settlement __instance, ref MobileParty mobileParty)
please revert this file

2024-11-20 00:06 UTC, garrettluskey commented on source/GameInterface/Services/Towns/Handlers/TownHandler.cs
please revert this file

2024-11-20 00:09 UTC, garrettluskey commented on source/GameInterface/Services/PartyComponents/Patches/Lifetime/MilitiaPartyComponentLifetimePatches.cs
Reverting this might not work with autosync. Let me know if that's the case

2024-11-20 12:58 UTC, georgyrudnev commented on source/GameInterface/Services/PartyComponents/Patches/Lifetime/MilitiaPartyComponentLifetimePatches.cs
Reverting it does not work with autosync. That was what I briefly mentioned in discord last week.

2024-11-20 12:59 UTC, georgyrudnev commented on source/GameInterface/Services/PartyComponents/Handlers/PartyComponentHandler.cs
> +        }
Although settlement is autosynced, during construction the settlement patch is somehow never called. (Neither with autosync nor with manual patching)
That is why I added this piece of code to ensure settlement is set during militiaPartyComponent construction.

2024-11-21 00:50 UTC, garrettluskey requested changes

2024-11-21 00:50 UTC, garrettluskey commented on source/Coop/Coop.csproj.user
Could you revert this file so it is not deleted?

2024-11-21 00:50 UTC, garrettluskey commented on source/ClientDebug/ClientDebug.csproj.user
Could you revert this file so it is not deleted?

2024-11-21 00:50 UTC, garrettluskey commented on source/GameInterface/Services/PartyComponents/Patches/Lifetime/MilitiaPartyComponentLifetimePatches.cs
> +        var message = new PartyComponentCreated(__instance, settlement.StringId);
settlement.StringId is not needed, can you remove from PartyComponentCreated?

2024-11-22 20:59 UTC, georgyrudnev commented on source/GameInterface/Services/PartyComponents/Patches/Lifetime/MilitiaPartyComponentLifetimePatches.cs
> +        var message = new PartyComponentCreated(__instance, settlement.StringId);
It is needed, see also my comment in PartyComponentHandler:
"Although settlement is autosynced, during construction the settlement patch is somehow never called. (Neither with autosync nor with manual patching)
That is why I added this piece of code to ensure settlement is set during militiaPartyComponent construction."

2024-11-22 21:20 UTC, georgyrudnev commented on source/GameInterface/Services/PartyComponents/Patches/Lifetime/MilitiaPartyComponentLifetimePatches.cs
> +        var message = new PartyComponentCreated(__instance, settlement.StringId);
I use that settlement.StringId in the PartyComponentHandler above.

2024-12-16 22:34 UTC, EgardA commented
LGTM!

2024-12-16 22:34 UTC, EgardA approved these changes

2024-12-16 22:35 UTC, merged